import type { ThemeColors, ThemeCategory, ThemeDefinition } from "@/types/themes";

export type { ThemeColors, ThemeCategory, ThemeDefinition };

function hexToRgba(hex: string, alpha: number): string {
  const num = parseInt(hex.replace("#", ""), 16);
  return `rgba(${(num >> 16) & 0xff}, ${(num >> 8) & 0xff}, ${num & 0xff}, ${alpha})`;
}

export function themeToCssVars(theme: ThemeDefinition): Record<string, string> {
  const { colors } = theme;
  return {
    "--bg-primary": colors.bgPrimary,
    "--bg-surface": colors.bgSurface,
    "--bg-elevated": colors.bgElevated,
    "--bg-hover": colors.bgHover,
    "--bg-active": colors.bgActive,
    "--text-primary": colors.textPrimary,
    "--text-secondary": colors.textSecondary,
    "--text-muted": colors.textMuted,
    "--border": colors.border,
    "--border-subtle": hexToRgba(colors.textPrimary, 0.08),
  };
}

export function getThemeById(id: string): ThemeDefinition {
  return THEMES.find((t) => t.id === id) ?? customThemeRegistry.get(id) ?? THEMES[0];
}

const customThemeRegistry = new Map<string, ThemeDefinition>();

export function registerCustomTheme(theme: ThemeDefinition) {
  customThemeRegistry.set(theme.id, theme);
}

export function unregisterCustomTheme(id: string) {
  customThemeRegistry.delete(id);
}

export function getAllThemes(): ThemeDefinition[] {
  return [...THEMES, ...customThemeRegistry.values()];
}



export function searchThemes(query: string): ThemeDefinition[] {
  const q = query.toLowerCase();
  return getAllThemes().filter(
    (t) =>
      t.name.toLowerCase().includes(q) ||
      t.description.toLowerCase().includes(q) ||
      t.category.includes(q)
  );
}

export const CATEGORIES: { id: ThemeCategory | "all"; label: string }[] = [
  { id: "all", label: "All" },
  { id: "dark", label: "Dark" },
  { id: "light", label: "Light" },
  { id: "colorful", label: "Colorful" },
  { id: "monochrome", label: "Monochrome" },
  { id: "nature", label: "Nature" },
  { id: "retro", label: "Retro" },
];

export const THEMES: ThemeDefinition[] = [
  {
    id: "dark",
    name: "Dark",
    description: "Warm dark tones",
    category: "dark",
    accent: "#f472b6",
    timerColor: "#efe3d4",
    colors: {
      bgPrimary: "#080604",
      bgSurface: "#16110d",
      bgElevated: "#2a221c",
      bgHover: "#382e26",
      bgActive: "#463b32",
      textPrimary: "#efe3d4",
      textSecondary: "#b8a99a",
      textMuted: "#8a7e72",
      border: "#382e26",
    },
  },
  {
    id: "midnight",
    name: "Midnight",
    description: "Cool dark tones",
    category: "dark",
    accent: "#818cf8",
    timerColor: "#e2e4f0",
    colors: {
      bgPrimary: "#0a0b10",
      bgSurface: "#13141c",
      bgElevated: "#1e202b",
      bgHover: "#2a2d3d",
      bgActive: "#363a4f",
      textPrimary: "#e2e4f0",
      textSecondary: "#a5a9c5",
      textMuted: "#7a7f9e",
      border: "#2a2d3d",
    },
  },
  {
    id: "oled",
    name: "OLED",
    description: "True black background",
    category: "dark",
    accent: "#22d3ee",
    timerColor: "#f0f0f0",
    colors: {
      bgPrimary: "#000000",
      bgSurface: "#0d0d0d",
      bgElevated: "#1a1a1a",
      bgHover: "#262626",
      bgActive: "#333333",
      textPrimary: "#f0f0f0",
      textSecondary: "#b0b0b0",
      textMuted: "#808080",
      border: "#262626",
    },
  },
  {
    id: "carbon",
    name: "Carbon",
    description: "Industrial dark gray",
    category: "monochrome",
    accent: "#38bdf8",
    timerColor: "#e5e7eb",
    colors: {
      bgPrimary: "#0f0f0f",
      bgSurface: "#191919",
      bgElevated: "#242424",
      bgHover: "#2e2e2e",
      bgActive: "#383838",
      textPrimary: "#e5e7eb",
      textSecondary: "#9ca3af",
      textMuted: "#6b7280",
      border: "#2e2e2e",
    },
  },
  {
    id: "slate",
    name: "Slate",
    description: "Clean gray minimal",
    category: "monochrome",
    accent: "#60a5fa",
    timerColor: "#f1f5f9",
    colors: {
      bgPrimary: "#0b0d10",
      bgSurface: "#16181d",
      bgElevated: "#22252b",
      bgHover: "#2e323a",
      bgActive: "#3b4049",
      textPrimary: "#f1f5f9",
      textSecondary: "#94a3b8",
      textMuted: "#64748b",
      border: "#2e323a",
    },
  },
  {
    id: "serika-dark",
    name: "Serika Dark",
    description: "Warm amber on dark",
    category: "dark",
    accent: "#e2b714",
    timerColor: "#d1d0c5",
    colors: {
      bgPrimary: "#323437",
      bgSurface: "#2c2e31",
      bgElevated: "#222224",
      bgHover: "#3a3c3f",
      bgActive: "#44464a",
      textPrimary: "#d1d0c5",
      textSecondary: "#646669",
      textMuted: "#4a4b4e",
      border: "#3a3c3f",
    },
  },
  {
    id: "dracula",
    name: "Dracula",
    description: "Deep purple-gray",
    category: "colorful",
    accent: "#bd93f9",
    timerColor: "#f8f8f2",
    colors: {
      bgPrimary: "#1e1e2e",
      bgSurface: "#282a36",
      bgElevated: "#343546",
      bgHover: "#404256",
      bgActive: "#4c4e66",
      textPrimary: "#f8f8f2",
      textSecondary: "#cdd6f4",
      textMuted: "#9399b2",
      border: "#404256",
    },
  },
  {
    id: "nord",
    name: "Nord",
    description: "Clean arctic blues",
    category: "colorful",
    accent: "#88c0d0",
    timerColor: "#eceff4",
    colors: {
      bgPrimary: "#2e3440",
      bgSurface: "#3b4252",
      bgElevated: "#434c5e",
      bgHover: "#4c566a",
      bgActive: "#5e687f",
      textPrimary: "#eceff4",
      textSecondary: "#d8dee9",
      textMuted: "#81a1c1",
      border: "#4c566a",
    },
  },
  {
    id: "tokyo-night",
    name: "Tokyo Night",
    description: "Deep blue city lights",
    category: "colorful",
    accent: "#7aa2f7",
    timerColor: "#c0caf5",
    colors: {
      bgPrimary: "#0f111a",
      bgSurface: "#1a1b2e",
      bgElevated: "#24283b",
      bgHover: "#2f334a",
      bgActive: "#3b3f58",
      textPrimary: "#c0caf5",
      textSecondary: "#a9b1d6",
      textMuted: "#565f89",
      border: "#2f334a",
    },
  },
  {
    id: "rose-pine",
    name: "Rose Pine",
    description: "Soft rose dawn",
    category: "colorful",
    accent: "#eb6f92",
    timerColor: "#e0def4",
    colors: {
      bgPrimary: "#191724",
      bgSurface: "#1f1d2e",
      bgElevated: "#2a273f",
      bgHover: "#353250",
      bgActive: "#403d5e",
      textPrimary: "#e0def4",
      textSecondary: "#c4a7e7",
      textMuted: "#6e6a86",
      border: "#353250",
    },
  },
  {
    id: "violet",
    name: "Violet",
    description: "Deep purple dark",
    category: "colorful",
    accent: "#c084fc",
    timerColor: "#ede9fe",
    colors: {
      bgPrimary: "#130b1e",
      bgSurface: "#1e1430",
      bgElevated: "#2c1f44",
      bgHover: "#3a2a58",
      bgActive: "#48356c",
      textPrimary: "#ede9fe",
      textSecondary: "#b8a8d9",
      textMuted: "#7a66a0",
      border: "#3a2a58",
    },
  },
  {
    id: "space",
    name: "Space",
    description: "Deep purple cosmos",
    category: "colorful",
    accent: "#a78bfa",
    timerColor: "#e2ddf2",
    colors: {
      bgPrimary: "#0a0718",
      bgSurface: "#141029",
      bgElevated: "#211c3d",
      bgHover: "#2e2850",
      bgActive: "#3d3566",
      textPrimary: "#e2ddf2",
      textSecondary: "#a99fd8",
      textMuted: "#7b6fb0",
      border: "#2e2850",
    },
  },
  {
    id: "ocean",
    name: "Ocean",
    description: "Deep blue aquatic",
    category: "nature",
    accent: "#38bdf8",
    timerColor: "#d6e6f0",
    colors: {
      bgPrimary: "#070d14",
      bgSurface: "#0f1a26",
      bgElevated: "#1a2b3d",
      bgHover: "#243b52",
      bgActive: "#2f4c66",
      textPrimary: "#d6e6f0",
      textSecondary: "#8fb8d4",
      textMuted: "#5e8aaa",
      border: "#243b52",
    },
  },
  {
    id: "forest",
    name: "Forest",
    description: "Deep green tones",
    category: "nature",
    accent: "#4ade80",
    timerColor: "#dce8d4",
    colors: {
      bgPrimary: "#0a1208",
      bgSurface: "#121e10",
      bgElevated: "#1f3018",
      bgHover: "#2a4020",
      bgActive: "#365028",
      textPrimary: "#dce8d4",
      textSecondary: "#9cb890",
      textMuted: "#709060",
      border: "#2a4020",
    },
  },
  {
    id: "matcha",
    name: "Matcha",
    description: "Green tea calm",
    category: "nature",
    accent: "#86efac",
    timerColor: "#dcfce7",
    colors: {
      bgPrimary: "#0a140e",
      bgSurface: "#0f1e15",
      bgElevated: "#162a1e",
      bgHover: "#1d3627",
      bgActive: "#244230",
      textPrimary: "#dcfce7",
      textSecondary: "#86c99e",
      textMuted: "#50966a",
      border: "#1d3627",
    },
  },
  {
    id: "mizu",
    name: "Mizu",
    description: "Aquatic blue calm",
    category: "nature",
    accent: "#8ad0f0",
    timerColor: "#e5f7ff",
    colors: {
      bgPrimary: "#1a2634",
      bgSurface: "#1e2d3d",
      bgElevated: "#243547",
      bgHover: "#2a3d52",
      bgActive: "#31465c",
      textPrimary: "#e5f7ff",
      textSecondary: "#7ab0d4",
      textMuted: "#527a9e",
      border: "#2a3d52",
    },
  },
  {
    id: "frozen",
    name: "Frozen",
    description: "Ice blue chill",
    category: "nature",
    accent: "#7dd3fc",
    timerColor: "#e0f2fe",
    colors: {
      bgPrimary: "#0f1a24",
      bgSurface: "#172636",
      bgElevated: "#1f344a",
      bgHover: "#28425e",
      bgActive: "#315072",
      textPrimary: "#e0f2fe",
      textSecondary: "#7ec8e3",
      textMuted: "#4891b5",
      border: "#28425e",
    },
  },
  {
    id: "coffee",
    name: "Coffee",
    description: "Rich warm browns",
    category: "dark",
    accent: "#fb923c",
    timerColor: "#e8d9c8",
    colors: {
      bgPrimary: "#100b08",
      bgSurface: "#1c1510",
      bgElevated: "#2d221a",
      bgHover: "#3d3026",
      bgActive: "#4d3d30",
      textPrimary: "#e8d9c8",
      textSecondary: "#b89f8a",
      textMuted: "#8a7560",
      border: "#3d3026",
    },
  },
  {
    id: "bushido",
    name: "Bushido",
    description: "Red samurai spirit",
    category: "colorful",
    accent: "#fc4343",
    timerColor: "#f0e6d2",
    colors: {
      bgPrimary: "#1a1310",
      bgSurface: "#241b17",
      bgElevated: "#302520",
      bgHover: "#3d2f28",
      bgActive: "#4a3a32",
      textPrimary: "#f0e6d2",
      textSecondary: "#c4a88a",
      textMuted: "#8a7060",
      border: "#3d2f28",
    },
  },
  {
    id: "cyberpunk",
    name: "Cyberpunk",
    description: "Neon city nights",
    category: "colorful",
    accent: "#ff00aa",
    timerColor: "#00ffaa",
    colors: {
      bgPrimary: "#0a0515",
      bgSurface: "#150a24",
      bgElevated: "#22103a",
      bgHover: "#301a4d",
      bgActive: "#3e2260",
      textPrimary: "#e0d0ff",
      textSecondary: "#a080ff",
      textMuted: "#7050aa",
      border: "#301a4d",
    },
  },
  {
    id: "sunset",
    name: "Sunset",
    description: "Warm orange coral",
    category: "nature",
    accent: "#ff6b6b",
    timerColor: "#ffe8d6",
    colors: {
      bgPrimary: "#1a0f0e",
      bgSurface: "#261714",
      bgElevated: "#36221c",
      bgHover: "#462d24",
      bgActive: "#56382c",
      textPrimary: "#ffe8d6",
      textSecondary: "#d4a88c",
      textMuted: "#a07058",
      border: "#462d24",
    },
  },
  {
    id: "honey",
    name: "Honey",
    description: "Warm golden glow",
    category: "nature",
    accent: "#fbbf24",
    timerColor: "#fef3c7",
    colors: {
      bgPrimary: "#1a1408",
      bgSurface: "#261e0c",
      bgElevated: "#342a12",
      bgHover: "#423618",
      bgActive: "#50421e",
      textPrimary: "#fef3c7",
      textSecondary: "#d4a84a",
      textMuted: "#9a7a30",
      border: "#423618",
    },
  },
  {
    id: "scarlet",
    name: "Scarlet",
    description: "Crimson red blaze",
    category: "colorful",
    accent: "#f87171",
    timerColor: "#fee2e2",
    colors: {
      bgPrimary: "#1a0a0a",
      bgSurface: "#26100e",
      bgElevated: "#341814",
      bgHover: "#42201a",
      bgActive: "#502820",
      textPrimary: "#fee2e2",
      textSecondary: "#d4908a",
      textMuted: "#9a5a54",
      border: "#42201a",
    },
  },
  {
    id: "monokai",
    name: "Monokai",
    description: "Classic vibrant dark",
    category: "dark",
    accent: "#a6e22e",
    timerColor: "#f8f8f2",
    colors: {
      bgPrimary: "#1b1d1e",
      bgSurface: "#232526",
      bgElevated: "#2d2f30",
      bgHover: "#383a3b",
      bgActive: "#434547",
      textPrimary: "#f8f8f2",
      textSecondary: "#cfcfc2",
      textMuted: "#75715e",
      border: "#383a3b",
    },
  },
  {
    id: "striker",
    name: "Striker",
    description: "Bold red accent",
    category: "monochrome",
    accent: "#d63031",
    timerColor: "#f0f0f0",
    colors: {
      bgPrimary: "#121212",
      bgSurface: "#1a1a1a",
      bgElevated: "#242424",
      bgHover: "#2e2e2e",
      bgActive: "#383838",
      textPrimary: "#f0f0f0",
      textSecondary: "#b0b0b0",
      textMuted: "#707070",
      border: "#2e2e2e",
    },
  },
  {
    id: "light",
    name: "Light",
    description: "Warm light tones",
    category: "light",
    accent: "#d9467a",
    timerColor: "#1a1410",
    colors: {
      bgPrimary: "#f5f0eb",
      bgSurface: "#e8e0d8",
      bgElevated: "#d9cfc4",
      bgHover: "#cdc1b4",
      bgActive: "#bfb1a2",
      textPrimary: "#1a1410",
      textSecondary: "#5c5146",
      textMuted: "#8a7e72",
      border: "#cdc1b4",
    },
  },
  {
    id: "sepia",
    name: "Sepia",
    description: "Warm paper tones",
    category: "retro",
    accent: "#a0522d",
    timerColor: "#3a2a1a",
    colors: {
      bgPrimary: "#f4ecd8",
      bgSurface: "#e8dcc4",
      bgElevated: "#dcc8a8",
      bgHover: "#d0bc94",
      bgActive: "#c4ac80",
      textPrimary: "#3a2a1a",
      textSecondary: "#6b5040",
      textMuted: "#9a8068",
      border: "#d0bc94",
    },
  },
  {
    id: "paper",
    name: "Paper",
    description: "Warm cream paper",
    category: "retro",
    accent: "#c44536",
    timerColor: "#2c1810",
    colors: {
      bgPrimary: "#faf3e8",
      bgSurface: "#f0e6d4",
      bgElevated: "#e4d6be",
      bgHover: "#d8c7aa",
      bgActive: "#ccb896",
      textPrimary: "#2c1810",
      textSecondary: "#5c4030",
      textMuted: "#8a7060",
      border: "#d8c7aa",
    },
  },
  {
    id: "iceberg",
    name: "Iceberg",
    description: "Cool blue light",
    category: "light",
    accent: "#3b82f6",
    timerColor: "#1a1a2e",
    colors: {
      bgPrimary: "#eef2f7",
      bgSurface: "#e2e8f0",
      bgElevated: "#d1d9e6",
      bgHover: "#c0cbd9",
      bgActive: "#aebdcc",
      textPrimary: "#1a1a2e",
      textSecondary: "#4a5b73",
      textMuted: "#7a8aa0",
      border: "#c0cbd9",
    },
  },
  {
    id: "glass",
    name: "Glass",
    description: "Frosted glass finish",
    category: "light",
    accent: "#38bdf8",
    timerColor: "#1a1a2e",
    colors: {
      bgPrimary: "#f0f4f8",
      bgSurface: "#e2e8f0",
      bgElevated: "#cbd5e1",
      bgHover: "#b4c5d9",
      bgActive: "#9eb5cf",
      textPrimary: "#1a1a2e",
      textSecondary: "#475569",
      textMuted: "#7689a3",
      border: "#b4c5d9",
    },
  },
  {
    id: "flower-power",
    name: "Flower Power",
    description: "Groovy warm retro",
    category: "retro",
    accent: "#ff6b9d",
    timerColor: "#fce4d6",
    colors: {
      bgPrimary: "#1a0e12",
      bgSurface: "#26151c",
      bgElevated: "#341d28",
      bgHover: "#422634",
      bgActive: "#503040",
      textPrimary: "#fce4d6",
      textSecondary: "#d4a0a0",
      textMuted: "#906870",
      border: "#422634",
    },
  },

  // ── New Uniques ──

  {
    id: "aurora",
    name: "Aurora",
    description: "Northern lights glow",
    category: "colorful",
    accent: "#34d399",
    timerColor: "#ecfdf5",
    colors: {
      bgPrimary: "#0a1412",
      bgSurface: "#0f1e1a",
      bgElevated: "#162a24",
      bgHover: "#1d362e",
      bgActive: "#244238",
      textPrimary: "#ecfdf5",
      textSecondary: "#6ee7b7",
      textMuted: "#4a9d7a",
      border: "#1d362e",
    },
  },
  {
    id: "candy",
    name: "Candy",
    description: "Sweet pastel pop",
    category: "colorful",
    accent: "#f472b6",
    timerColor: "#fdf2f8",
    colors: {
      bgPrimary: "#1a0e18",
      bgSurface: "#261524",
      bgElevated: "#341d32",
      bgHover: "#422640",
      bgActive: "#502e4e",
      textPrimary: "#fdf2f8",
      textSecondary: "#f9a8d4",
      textMuted: "#b06a96",
      border: "#422640",
    },
  },
  {
    id: "lava",
    name: "Lava",
    description: "Molten volcanic glow",
    category: "colorful",
    accent: "#f97316",
    timerColor: "#fff7ed",
    colors: {
      bgPrimary: "#140a06",
      bgSurface: "#1e1008",
      bgElevated: "#2a180c",
      bgHover: "#362010",
      bgActive: "#422814",
      textPrimary: "#fff7ed",
      textSecondary: "#fdba74",
      textMuted: "#b0763a",
      border: "#362010",
    },
  },
  {
    id: "mint",
    name: "Mint",
    description: "Fresh cool mint",
    category: "nature",
    accent: "#2dd4bf",
    timerColor: "#f0fdfa",
    colors: {
      bgPrimary: "#071210",
      bgSurface: "#0b1d1a",
      bgElevated: "#112a26",
      bgHover: "#173732",
      bgActive: "#1d443e",
      textPrimary: "#f0fdfa",
      textSecondary: "#5eead4",
      textMuted: "#3aa88a",
      border: "#173732",
    },
  },
  {
    id: "chocolate",
    name: "Chocolate",
    description: "Deep cocoa browns",
    category: "dark",
    accent: "#d97706",
    timerColor: "#fef3c7",
    colors: {
      bgPrimary: "#0f0806",
      bgSurface: "#1a100a",
      bgElevated: "#261810",
      bgHover: "#322016",
      bgActive: "#3e281c",
      textPrimary: "#fef3c7",
      textSecondary: "#d4a050",
      textMuted: "#9a7028",
      border: "#322016",
    },
  },
  {
    id: "nebula",
    name: "Nebula",
    description: "Cosmic purple dust",
    category: "colorful",
    accent: "#e879f9",
    timerColor: "#faf5ff",
    colors: {
      bgPrimary: "#100916",
      bgSurface: "#1a0f24",
      bgElevated: "#261734",
      bgHover: "#321f44",
      bgActive: "#3e2754",
      textPrimary: "#faf5ff",
      textSecondary: "#d8b4fe",
      textMuted: "#9a72c0",
      border: "#321f44",
    },
  },
  {
    id: "mocha",
    name: "Mocha",
    description: "Creamy coffee latte",
    category: "retro",
    accent: "#a16207",
    timerColor: "#faf5eb",
    colors: {
      bgPrimary: "#faf5eb",
      bgSurface: "#f0ead8",
      bgElevated: "#e4dcc2",
      bgHover: "#d8ceaa",
      bgActive: "#ccc092",
      textPrimary: "#3a2810",
      textSecondary: "#6b5030",
      textMuted: "#9a8060",
      border: "#d8ceaa",
    },
  },
  {
    id: "ash",
    name: "Ash",
    description: "Cool gray embers",
    category: "monochrome",
    accent: "#a3a3a3",
    timerColor: "#f5f5f5",
    colors: {
      bgPrimary: "#0e0e0e",
      bgSurface: "#181818",
      bgElevated: "#222222",
      bgHover: "#2c2c2c",
      bgActive: "#363636",
      textPrimary: "#f5f5f5",
      textSecondary: "#a3a3a3",
      textMuted: "#737373",
      border: "#2c2c2c",
    },
  },
  {
    id: "whiteout",
    name: "Whiteout",
    description: "Pure white minimal",
    category: "monochrome",
    accent: "#6366f1",
    timerColor: "#0a0a0a",
    colors: {
      bgPrimary: "#ffffff",
      bgSurface: "#f5f5f5",
      bgElevated: "#e5e5e5",
      bgHover: "#d4d4d4",
      bgActive: "#a3a3a3",
      textPrimary: "#0a0a0a",
      textSecondary: "#525252",
      textMuted: "#a3a3a3",
      border: "#d4d4d4",
    },
  },
  {
    id: "abyss",
    name: "Abyss",
    description: "Deepest ocean floor",
    category: "dark",
    accent: "#06b6d4",
    timerColor: "#ecfeff",
    colors: {
      bgPrimary: "#020617",
      bgSurface: "#070d22",
      bgElevated: "#0e1530",
      bgHover: "#161d3e",
      bgActive: "#1e254c",
      textPrimary: "#ecfeff",
      textSecondary: "#67e8f9",
      textMuted: "#3b82c4",
      border: "#161d3e",
    },
  },
  {
    id: "embers",
    name: "Embers",
    description: "Glowing orange coals",
    category: "colorful",
    accent: "#f59e0b",
    timerColor: "#fffbeb",
    colors: {
      bgPrimary: "#140c06",
      bgSurface: "#1e1208",
      bgElevated: "#2a1a0c",
      bgHover: "#362210",
      bgActive: "#422a14",
      textPrimary: "#fffbeb",
      textSecondary: "#fcd34d",
      textMuted: "#b0802a",
      border: "#362210",
    },
  },
  {
    id: "tundra",
    name: "Tundra",
    description: "Frosty pale blues",
    category: "light",
    accent: "#67e8f9",
    timerColor: "#0c1a20",
    colors: {
      bgPrimary: "#e8f4f8",
      bgSurface: "#dceaf0",
      bgElevated: "#ccdee6",
      bgHover: "#bcd2dc",
      bgActive: "#acc6d2",
      textPrimary: "#0c1a20",
      textSecondary: "#3a6878",
      textMuted: "#7098aa",
      border: "#bcd2dc",
    },
  },
  {
    id: "midori",
    name: "Midori",
    description: "Japanese forest green",
    category: "nature",
    accent: "#22c55e",
    timerColor: "#f0fdf4",
    colors: {
      bgPrimary: "#0c1408",
      bgSurface: "#121e0c",
      bgElevated: "#1a2a12",
      bgHover: "#223618",
      bgActive: "#2a421e",
      textPrimary: "#f0fdf4",
      textSecondary: "#86efac",
      textMuted: "#4aa06a",
      border: "#223618",
    },
  },
  {
    id: "sunny",
    name: "Sunny",
    description: "Bright warm yellow",
    category: "light",
    accent: "#f97316",
    timerColor: "#1a1408",
    colors: {
      bgPrimary: "#fefce8",
      bgSurface: "#fef9c3",
      bgElevated: "#fde68a",
      bgHover: "#fcd34d",
      bgActive: "#fbbf24",
      textPrimary: "#1a1408",
      textSecondary: "#78350f",
      textMuted: "#92400e",
      border: "#fcd34d",
    },
  },
  {
    id: "pearl",
    name: "Pearl",
    description: "Soft opal elegance",
    category: "light",
    accent: "#ec4899",
    timerColor: "#1a1420",
    colors: {
      bgPrimary: "#f8f4f8",
      bgSurface: "#eee6ee",
      bgElevated: "#e0d4e0",
      bgHover: "#d2c4d2",
      bgActive: "#c4b4c4",
      textPrimary: "#1a1420",
      textSecondary: "#5c4860",
      textMuted: "#8a7a90",
      border: "#d2c4d2",
    },
  },
];


